adviseME/accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('profile/', views.Profile.as_view(), name='profile'),

]

adviseME/adviseME/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from adviseMeApp import views


urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('', include('adviseMeApp.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),

]

adviseME/adviseMeApp/urls.py
from django.urls import path
from . import views

app_name = 'adviseMeApp'

urlpatterns = [
    path('topic/<int:pk>', views.TopicView.as_view(), name='topicview'),
    path('topic/add', views.TopicCreate.as_view(), name='topicCreate'),
    path('topic/<int:pk>/comment', views.CommentCreate.as_view(), name='commentCreate'),

    path('comment/<int:pk>', views.vote, name='vote'),
]

adviseME/accounts/models.py
from django.db import models

# Create your models here.

adviseME/adviseMeApp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Topic(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    text= models.CharField(max_length=500)


class Comment(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.CharField(max_length=500)
    vote = models.IntegerField(default=0)

    class Meta:
        ordering = ['-vote']

adviseME/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.views import generic
from django.urls import reverse_lazy
from adviseMeApp.models import Topic, Comment

# Create your views here.


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'


class Profile(generic.DetailView):
    template_name = 'registration/profile.html'
    def get_queryset(self):
        if self.request.user.is_authenticated:
            return Topic.objects.filter(user=self.request.user.id)


    def get_object(self):
        return self.request.user

adviseME/adviseMeApp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic
from .models import Topic, Comment
from django.http import HttpResponseRedirect

# Create your views here.

class Home(generic.ListView):
    template_name = 'home.html'
    model = Topic
    # paginate_by = 7


class TopicView(generic.DetailView):
    model = Topic
    template_name = 'topicView.html'


class TopicCreate(generic.edit.CreateView):
    model = Topic
    fields = ['title', 'text']
    success_url = '/'


    def form_valid(self, form):
        form.instance.user = self.request.user
        #success_url = '/topic/'+Topic.objects.get()

        return super().form_valid(form)

# 04 May 2019 added. This is to create add comments page
class CommentCreate(generic.edit.CreateView):
    model = Comment
    fields = ['text']
    success_url = '/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
# End of this block

def vote(request, pk):
    comment = Comment.objects.get(pk=pk)
    if request.POST['vote'] == '+':
        comment.vote +=1
        print(f"Vote +1 comment {comment.id}")
    elif request.POST['vote'] == '-':
        comment.vote -=1
        print(f"Vote -1 comment {comment.id}")

    comment.save()
    return redirect('adviseMeApp:topicview',pk=comment.topic_id)

adviseME/templates/adviseMeApp/topic_form.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

adviseME/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

adviseME/templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
      Hi {{ user.username }}!
      <br>
      <p><a href="{% url 'logout' %}">logout</a> | <a href="{% url 'profile' %}">profile</a> </p>

{% else %}
    You are not logged in. Please <a href="{% url 'login' %}">login</a> or <a href="{% url 'signup' %}">signup</a> to enjoy more features.
{% endif %}

<br><br>

{% if topic_list  %}
    {% for topic in topic_list %}
        {% if topic.user_id == user.id %}
            <p><font size="4" color="green">{{topic.title}}<br>{{topic.text}}</font></p>
        {% else %}
            <h3><font size="3" color="black">{{topic.title}} <br>{{topic.text}}</font></p>
        {% endif %}

        {% for comment in topic.comment_set.all %}
        {{comment.id}}: {{comment.text}}
            <h4>Votes:{{comment.vote}}</h4>
        {% endfor %}
        <a href ="{% url 'adviseMeApp:topicview' topic.id %}"> Read here details and the comments and Vote!</a>
        <hr>
    {%  endfor %}

{% endif %}

{% endblock %}

adviseME/templates/topicView.html
{% extends 'base.html' %}

{% block title %}Topic Detail{% endblock %}

{% block content %}

{% if topic %}
    <h2>{{topic.title}}</h2>
    <br>{{topic.text}}
    <br><br><br>
    {% for comment in topic.comment_set.all %}
        {{comment.id}}: {{comment.text}}<br><br>
        {% if user.is_authenticated %}
        <form action="{% url 'adviseMeApp:vote' comment.id %}" method="post">
            {% csrf_token %}
            <h3>Votes: <input type="submit" value="-" name="vote">
                ( {{comment.vote}} )
            <input type="submit" value="+" name="vote"></h3>
        </form>
        <br><br>
        {% endif %}
    {% endfor %}

{% endif %}
{% endblock %}